name: Docker Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker_release:
    # gh-reusable docker-release.yaml @ v0.0.6
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@ca231d10a9645621e4454a210f78f2e07ea4650d
    with:
      image: ${{ vars.DOCKER_USERNAME }}/helm-hub
      dockerhub_username: ${{ vars.DOCKER_USERNAME }}
      context: "."
      dockerfile: "./Dockerfile"
      # Current runtime target is amd64 only.
      platforms: "linux/amd64"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
