name: Docker Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# example change to trigger ci 4

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  docker_release:
    # gh-reusable docker-release.yaml @ v0.0.6:
    # https://github.com/mbround18/gh-reusable/releases/tag/v0.0.6
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@dagger/io
    with:
      image: ${{ vars.DOCKER_USERNAME }}/helm-hub
      dockerhub_username: ${{ vars.DOCKER_USERNAME }}
      context: "."
      dockerfile: "./Dockerfile"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
